import type { Employee } from '../types';

export const mockEmployees: Employee[] = [
    {
        id: 1,
        name: "Ana García",
        email: "ana.garcia@empresa.com",
        position: "Desarrolladora Frontend",
        department: "Tecnología",
        salary: 8500,
        hireDate: "2022-03-15",
        status: "active",
        role: "employee",
        avatarUrl: "https://i.pravatar.cc/64?img=1",
    },
    {
        id: 2,
        name: "Carlos Martínez",
        email: "carlos.martinez@empresa.com",
        position: "Gerente de RRHH",
        department: "Recursos Humanos",
        salary: 12000,
        hireDate: "2019-07-01",
        status: "active",
        role: "hr",
    },
    {
        id: 3,
        name: "María López",
        email: "maria.lopez@empresa.com",
        position: "Contadora Senior",
        department: "Finanzas",
        salary: 9500,
        hireDate: "2021-01-20",
        status: "on_leave",
        role: "employee",
    },
    {
        id: 4,
        name: "Roberto Silva",
        email: "roberto.silva@empresa.com",
        position: "Administrador del Sistema",
        department: "Tecnología",
        salary: 15000,
        hireDate: "2018-05-10",
        status: "active",
        role: "admin",
    },
    {
        id: 5,
        name: "Gabriel Ochoa",
        email: "Gabriel.Ochoa@empresa.com",
        position: "Gerente",
        department: "Ventas",
        salary: 9250,
        hireDate: "2019-08-01",
        status: "inactive",
        role: "employee",
    },
    {
        id: 6,
        name: "Alejandro Morataya",
        email: "alejandro.morataya@empresa.com",
        position: "Ejecutivo ",
        department: "Ventas",
        salary: 67000,
        hireDate: "2025-11-11",
        status: "inactive",
        role: "employee",
    },
    {
        id: 7,
        name: "Sofía Ramírez",
        email: "sofia.ramirez@empresa.com",
        position: "Desarrolladora Backend",
        department: "Tecnología",
        salary: 10000,
        hireDate: "2023-02-14",
        status: "active",
        role: "employee",
        avatarUrl: "https://i.pravatar.cc/64?img=2",
    },
    {
        id: 8,
        name: "Diego Rodríguez",
        email: "diego.rodriguez@empresa.com",
        position: "Analista de Datos",
        department: "Tecnología",
        salary: 9800,
        hireDate: "2022-09-22",
        status: "active",
        role: "employee",
        avatarUrl: "https://i.pravatar.cc/64?img=3",
    },
    {
        id: 9,
        name: "Patricia Flores",
        email: "patricia.flores@empresa.com",
        position: "Especialista en Nómina",
        department: "Recursos Humanos",
        salary: 8200,
        hireDate: "2021-05-10",
        status: "active",
        role: "employee",
        avatarUrl: "https://i.pravatar.cc/64?img=4",
    },
    {
        id: 10,
        name: "Javier Hernández",
        email: "javier.hernandez@empresa.com",
        position: "Auditor Financiero",
        department: "Finanzas",
        salary: 11500,
        hireDate: "2020-01-15",
        status: "active",
        role: "employee",
        avatarUrl: "https://i.pravatar.cc/64?img=5",
    },
    {
        id: 11,
        name: "Laura Delgado",
        email: "laura.delgado@empresa.com",
        position: "Supervisora de Operaciones",
        department: "Operaciones",
        salary: 8900,
        hireDate: "2022-06-30",
        status: "on_leave",
        role: "employee",
        avatarUrl: "https://i.pravatar.cc/64?img=6",
    },
    {
        id: 12,
        name: "Miguel Ángel Santos",
        email: "miguelangel.santos@empresa.com",
        position: "Representante de Ventas",
        department: "Ventas",
        salary: 7500,
        hireDate: "2023-04-03",
        status: "active",
        role: "employee",
        avatarUrl: "https://i.pravatar.cc/64?img=7",
    },
    {
        id: 13,
        name: "Valentina Cortés",
        email: "valentina.cortes@empresa.com",
        position: "Diseñadora UX/UI",
        department: "Tecnología",
        salary: 10500,
        hireDate: "2023-08-21",
        status: "active",
        role: "employee",
        avatarUrl: "https://i.pravatar.cc/64?img=8",
    },
    {
        id: 14,
        name: "Eduardo Vázquez",
        email: "eduardo.vazquez@empresa.com",
        position: "Coordinador de Logística",
        department: "Operaciones",
        salary: 7800,
        hireDate: "2021-11-08",
        status: "inactive",
        role: "employee",
        avatarUrl: "https://i.pravatar.cc/64?img=9",
    },
    {
        id: 15,
        name: "Isabella Mendoza",
        email: "isabella.mendoza@empresa.com",
        position: "Especialista en Marketing",
        department: "Ventas",
        salary: 8600,
        hireDate: "2022-03-17",
        status: "active",
        role: "employee",
        avatarUrl: "https://i.pravatar.cc/64?img=10",
    }
];